# ===============================
# = lOG OUTPUT
# ===============================
logging.file.name=logs/out.log
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws.client.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.server.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
logging.level.org.springframework.ws.server.MessageTracing.received=TRACE
# ===============================
# = DATA SOURCE (Connection url for the database "MyHotel")
# ===============================
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://${DB_HOSTNAME:MYHOTEL-PC\\MSSQLSERVER}:${DB_PORT:1433};databaseName=${DB_DB_NAME:ScadaNetDb;integratedSecurity=true;}
# ===============================
# = Username and password DEV -- Not in use in favor of integrated security
# ===============================
# db.username=${DB_USERNAME:*****}
# db.password=${DB_PASSWORD:*****}
# ===============================
# = Hibernate configuration
# ===============================
hibernate.dialect=org.hibernate.dialect.SQLServerDialect
hibernate.show_sql=false
hibernate.hbm2ddl.auto=update
spring.jpa.hibernate.ddl-auto=update
# ===============================
# = C3P0 Connection pool configuration
# ===============================
hibernate.c3p0.max_size=${DB_POOL_MAX_SIZE:50}
hibernate.c3p0.min_size=${DB_POOL_MIN_SIZE:10}
hibernate.c3p0.idle_max_idle_time=${DB_POOL_IDLE_MAX_TIME:1800}
hibernate.c3p0.idle_test_period=${DB_POOL_IDLE_TEST_PERIOD:600}
# ===============================
# = Conf
# ===============================
app.environment=${ENVIRONMENT:LOCAL}
job.batch.chunk.size=${CHUNK_SIZE:10}
spring.batch.job.enabled=true
spring.main.allow-bean-definition-overriding=false
spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.table-prefix=BATCH_
# Aca va el nombre del job a ejecutar, SI ESTA VACIO, SE EJECUTAN TODOS Y SI EL NOMBRE NO COINCIDE CON NINGUNO JOB NO SE EJECUTA NADA
spring.batch.job.names=${JOB_NAME:dgaSyncJob}
# ===============================
# = Misc
# ===============================
properties.filename=${PROPERTIES_FILENAME:dga_sync_properties.json}
dga.login.user=${DGA_USER:1-9}
dga.login.password=${DGA_PASSWORD:*****}
dga.service.url=${SERVICE_URL:https://snia.mop.gob.cl/controlextraccion/datosExtraccion/SendDataExtraccionService}
dga.wsld.url=${WSDL_URL:https://snia.mop.gob.cl/controlextraccion/wsdl/datosExtraccion/SendDataExtraccionService?wsdl}
hours.regression.retry=${HOURS_REGRESSION_RETRY:24}
hours.regression.trigger=${HOURS_REGRESSION_TRIGGER:2}
hours.search.offset=${HOURS_OFFSET:1}
dga.webservice.max.attempts=${DGA_WEBSERVICE_MAX_ATTEMPTS:3}
dga.webservice.seconds.delay=${DGA_WEBSERVICE_SECONDS_DELAY:10}